server:
  port: 8980
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-database:5432/data_store?currentSchema=ds_server&stringtype=unspecified
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

datastore:
  server:
    upload-session:
      chunk-size: 1MB
      min-chunk-size: 512KB
      upload-chunk-timeout: 5m
      upload-session-timeout: 7d
      processing-thread-count: 1