name: 'data-store'

services:
  postgres-database:
    image: 'postgres:16-alpine'
    shm_size: 128mb
    environment:
      POSTGRES_DB: 'data_store'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - network-back
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 2s
      timeout: 10s
      retries: 25
    restart: always

  server:
    build: .
    environment:
      POSTGRES_HOST: 'postgres-database'
      POSTGRES_DB: 'data_store'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - network-back
      - network-front
    ports:
      - 8980:8980
    depends_on:
      postgres-database:
        condition: service_healthy
        restart: true
    restart: always


volumes:
  postgres-data:
    name: 'volume-data-store-postgres-data'


networks:
  network-back:
    name: 'network-data-store-back'
    driver: bridge
    internal: true

  network-front:
    name: 'network-data-store-front'
    driver: bridge